#工程端口号
server:
  port: 1001

spring:
  application:
    name: service-provider #工程名，后面各个服务间调用接口要用到

#eureka注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #eureka服务器所在的地址

