#工程端口号
server:
  port: 4002

spring:
  application:
    name: feign-consumer #工程名，后面各个服务间调用接口要用到
  rabbitmq:
    host: 14.23.124.140
    port: 40071
    username: guest
    password: guest
  #开启sleuth链路追踪功能  true
  sleuth:
    web:
      client:
        enabled: true
    # 设置为1.0时，链路的信息100%收集到zipkin-server  最大为1.0，假如收集20%即为0.2
    sampler:
      probability: 1.0
  #配置zipkin服务器的地址
  zipkin:
    base-url: http://localost:9411

#eureka注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #eureka服务器所在的地址

# 支持hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000 #超时时间

#结合hystrix dashboard控制面板时，通过HTTP实现一个actuator端点，它需要被启用并公开，默认是只公开heath和info两个端点
management:
    endpoints:
        web:
            exposure:
                include: '*'