#工程端口号
server:
  port: 8761

#eureka注册中心地址
eureka:
  client:
    registerWithEureka: false #是否注册自身到eureka服务器，本子工程就是eureka服务器，所以false
    fetchRegistry: false #是否需要从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #eureka服务器所在的地址

#由于需要用到rabbitmq，所以也要配置rabbitmq  不配置之启动也能访问到eureka注册中心，但会提示mq连接报错  rabbitmq控制台访问地址 http://localhost:15672
spring:
  application:
    name: eureka-server #工程名
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest