#工程端口号
server:
  port: 5002

spring:
  application:
    name: hystrix-turbine #工程名，后面各个服务间调用接口要用到
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#eureka注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #eureka服务器所在的地址

#聚合的工程  这里演示聚合ribbon-consumer,feign-consumer这两个消费工程
turbine:
  aggregator:
    cluster-config: default
  app-config: ribbon-consumer,feign-consumer
  cluster-name-expression: new String("default")
